### ISSUE TITLE
Some thing wrong when server update 

### ISSUE THREAD

**Issue by nguoingoai** [mgierw/auto-foe#10]
1. 
![screen shot 2017-06-17 at 8 59 30 am](https://user-images.githubusercontent.com/28948005/27249268-99ff9bda-533b-11e7-8572-0bc2ae637c82.png)
Can not see the number of good any more , the number of population , diamond , forge point , silver is still oK

2. Not create trading any more (I think because of the above problem ) 

3. I can see the The Lord's Manor (Wczesne Średniowiecze) in the residential list  ,but can not see the house from event Historical Questline - Shah Jahan Hedge_Maze I had complete the Quest.

**Comment by Inearthed74** [comment]
same here

**Comment by mgierw** [comment]
Commited some changes for 1. and 2.:
https://github.com/mgierw/auto-foe/commit/7ae78f95c8d531eca596db9ce5baac0f42b2536d
Commited changes for 3. without a test (because I don't have such a building) - it should be in Production Buildings Tab:
https://github.com/mgierw/auto-foe/commit/d438cb9d7562c752c891a637df63630e4536194c

Please check it out.

**Comment by nguoingoai** [comment]
Working Greate ! Thank you so much
